### ISSUE TITLE
Links with minicons styling

### ISSUE THREAD

**Issue by iuloshi** [cfpb/cf-typography#10]
Have you guys by chance coded out examples of links with minicons? Standard is that minicons aren't underlined, but still Pacific and should have the same states as the rest of the link text.

Can't seem to find any in [this repo's docs](https://cfpb.github.io/cf-typography/docs/) or the [buttons docs page](http://cfpb.github.io/cf-buttons/docs/). If not, no worries! Just ran into this in the Design Manual.

![screen shot 2014-04-23 at 12 49 06 pm](https://cloud.githubusercontent.com/assets/1676307/2780411/58fe8066-cb07-11e3-818b-3922aa3d1f35.png)

**Comment by KimberlyMunoz** [comment]
Jump links and other styles from cfgov-refresh were added in 0.6.0 which was released earlier this year. Closing this issue!
