### ISSUE TITLE
Responsively adjust type hierarchy scale

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-typography#2]
Via @Scotchester

> Awesome article: http://typecast.com/blog/a-more-modern-scale-for-web-typography

**Comment by KimberlyMunoz** [comment]
Hey @Scotchester, since we already have patterns for headings to shrink at certain levels should we close this issue?

Thanks!

**Comment by Scotchester** [comment]
Yep! Looks like we just never came back around to it.
