### ISSUE TITLE
Provide list__icons modifier that indents multi-line text

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-typography#29]
Instead of this for multi-line text in the list:

![screen shot 2015-03-18 at 4 04 26 pm](https://cloud.githubusercontent.com/assets/704760/6718284/07b7a004-cd89-11e4-8cc9-7c834c2b9385.png)

Provide a modifier to produce this:

![screen shot 2015-03-18 at 4 07 58 pm](https://cloud.githubusercontent.com/assets/704760/6718286/102abc94-cd89-11e4-9ba1-b286a2f0a312.png)

**Comment by Scotchester** [comment]
I'd say that should be the default and only behavior.

**Comment by anselmbradford** [comment]
:+1: :+1:  I was thinking there could be occurrences where something analogous to [initiums](http://oldandoutofprint.blogspot.com/2012/08/in-written-or-published-work-initial-is.html) might be used, but yes, then it wouldn't be a list that would be used as the base pattern!

**Comment by KimberlyMunoz** [comment]
@anselmbradford: Was this fixed in the two following PRs?

**Comment by anselmbradford** [comment]
Looks like it.
