### ISSUE TITLE
Does base list pattern exist?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-typography#30]
The docs have code snippets like `<ul class="list list__unstyled">` and cheatsheet `.list.list__unstyled`, which show a `.list` class. However, this class doesn't appear required for implementing the patterns and I can't find it in the docs. Does it actually exist or can it be removed from the docs?

**Comment by Scotchester** [comment]
There's no styling actually attached to that class. It exists merely as a reminder that it's the name of the block, whence flow modifiers like `__unstyled` and elements like `_item`.

**Comment by anselmbradford** [comment]
Mm, thanks just seeing that, in e.g. `.list_icon`. Do other parts of CF work like this (with undeclared base classes)? I'm still getting a hang of BEM, but wouldn't `list__unstyled` alone imply the name of the block just as well?

For context, I ran into this with this code block:

```css
    ul {
        .list__links();
        .list__icons();
```

When referencing the docs, it appeared like there may be styles associated with `list` that had been erroneously left out. But of course the following throws an error because `.list` doesn't exist:

```css
    ul {
        .list();
        .list__links();
        .list__icons();
```

**Comment by Scotchester** [comment]
It's the only example that I know of with an undeclared base class. No wait, I think I just saw another. Well, it's an example from cfgov-refresh, not CF, but check out `.header` (`_includes/header.html` and `static/css/header.less`). FWIW, the empty `.header { }` declaration probably shouldn't have been left there. I think I had stuff in it, removed those things, but left it temporarily in case I wanted to put stuff back in it, and then never did.

Interesting scenario that you present. Getting rid of the `.list` class in markup examples wouldn't have prevented that stumbling block, though. It would still look like `.list()` was erroneously omitted.

**Comment by anselmbradford** [comment]
Ahh, cool, yeah saw the empty `.header { }` earlier and had removed it in a local branch that never ended up in a PR. Good to get verification it's not needed.

So in the scenario I had, the original code block was:

```
    ul {
        .list__unstyled();
        .list__links();
        .list__icons();
```

Then I saw in the source code that `.list__icons()` includes `.list__unstyled()`, so I removed that from the block. Then seeing `list` included in the docs next to, e.g., `<ul class="list list__icons">`, seems to imply `list` is adding its own styles that aren't included in `list_icons` since they are listed alongside each other, even though `list_icons` _could_ include them in its own declaration, like it does with `list__unstyled()`. 

Throwing an error when `.list()` is added instead of having an empty rule is probably the proper behavior, but just my 2cents that having an undeclared class in the docs may lead implementors to think the `list` class is required for proper behavior of the block, when it isn't.

**Comment by Scotchester** [comment]
I see what you mean.

It's a tough situation. I guess my opinion would be better to err on the side of including classes that aren't currently needed in the markup, but make the BEM relationships more explicit, and could be used in the future.

Doesn't solve your issue of getting a compilation error when trying to use `.list()`, though.

**Comment by anselmbradford** [comment]
Perhaps a section below the `Theme variables` in the beginning of the docs that lists undeclared classes?

**Comment by himedlooff** [comment]
This kind of thing is weird but necessary, unfortunately. There should be some standardization though. Always including an empty rule might be the friendliest thing to do. Especially for people who don't want to understand BEM fully.

**Comment by anselmbradford** [comment]
> Always including an empty rule might be the friendliest thing to do.

A gotcha with that that comes to mind is that people might in some cases include `.list()` and in some cases not, and in both scenarios see no errors because everything is fine... until one day we decide we actually want to add styles to `list` and it borks some existing implementations and not others.

The existing behavior of throwing an error when the undeclared class is added isn't as friendly, but is probably the way to go because it keeps everyone from adding this class through the `.list()` syntax (though it could be added as `list` in the markup still).

**Comment by himedlooff** [comment]
Good point. I hadn't considered what would happen if we eventually wanted to add some rules to `.list`.

> The existing behavior of throwing an error when the undeclared class is added isn't as friendly, but is probably the way to go because it keeps everyone from adding this class through the .list() syntax (though it could be added as list in the markup still).

Either way something's going to break. Not declaring the `list()` mixin helps people in Less but not in HTML because they can use the `list` class, and if we ever add anything to that selector it could potentially alter the style of their page. Throwing the Less error doesn't seem like a complete solution. Asking everyone to use `list()` in Less and `list` in the markup is more consistent. Consistency is an important thing.

I wonder how much use these modifiers get as classes in the HTML VS as mixins in Less. Maybe that will help us veer in a direction.

**Comment by KimberlyMunoz** [comment]
@anselmbradford: The question seems answered, if there's a follow-up issue, can you post in Capital Framework? Thanks!
