### ISSUE TITLE
LICENSE link in Readme is broken

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-typography#31]
The `LICENSE` link at the bottom of the Readme is broken, because a LICENSE file is not included in the project. Either one should be added or the link should be removed.

**Comment by Scotchester** [comment]
This repo harkens back to a time when we called that file `COPYING.txt` for some reason. That file should just be renamed `LICENSE`.

**Comment by anselmbradford** [comment]
Cool, thanks for the clarification!
