### ISSUE TITLE
Make .date mixin?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-typography#37]
The [`.date` class](https://github.com/cfpb/cf-typography/blob/gh-pages/src/cf-typography.less#L231-L235) seems a little inflexible. Some areas may want to use a date and designate it with a `.date` class, but not have it be `h5()`. Would it make sense to make this a mixin instead? Implementing projects could do:

```
.date {
    .date();
}
```

If they want the whole site to follow the generic date styles, or:

```
.example-page {
    .date {
        .date();
    }
}
```

If they wanted to only apply the date format to a page on the site.

As it is now if a page wanted to override the date styles, a new date class either needs to be created or each style needs to be overridden. Any thoughts on this?

**Comment by himedlooff** [comment]
Why not have modifiers instead? Like `.date__small`, `.date__medium`, `.date__large`?

**Comment by jimmynotjim** [comment]
I think we need to be clear on the use cases and requirements before making either choice. I could see scenarios where the color might need to change as well, which would lead to a crazy number of modifiers. Let's get the details nailed down before proceeding with a solution.
