### ISSUE TITLE
Why aren't variables at top of file?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-typography#39]
Why aren't these variables https://github.com/cfpb/cf-typography/blob/gh-pages/src/cf-typography.less#L367-L369 at the top of the file, like these [here](https://github.com/cfpb/cf-typography/blob/gh-pages/src/cf-typography.less#L50-L86)? Also should these be included in the CF theme overrides file?

**Comment by Scotchester** [comment]
Maybe because they can't "safely" be set to any arbitrary value without breaking the visual effect? Not sure, though.

@himedlooff ?

**Comment by anselmbradford** [comment]
Yeah, looking at it again I guess the top variables are only for color. What you wrote makes sense. If the pattern is color variables are moved to the top and local variables are contained in the style block they're used in, that seems fine. However, things like [this](https://github.com/cfpb/cf-typography/blob/gh-pages/src/cf-typography.less#L699) are confusing. `@font-size` is defined in `.styled-link`, but is used throughout `cf-typography.less`, even before it's defined on line 699. And it's then defined again on https://github.com/cfpb/cf-typography/blob/gh-pages/src/cf-typography.less#L1167. I assume `@font-size` is set in another CF package? Is that right? And then the two places its set in cf-typography is overriding the default. Seems like these maybe should be pulling out into variables in cf-theme-overrides.

**Comment by Scotchester** [comment]
`@font-size` is a tricky one. I'm actually not sure why it's defined there in `.styled-link`. It's not really needed there.

But if you look at every other example of `@font-size` in cf-typography, you'll see that each of them are based on one of our standard heading styles, which are called as mixins. When that happens, the value of `@font-size` is the one specified in that heading style that's mixed in. This lets us ensure that various em calculations are based on the correct local font size.

Make sense?

**Comment by himedlooff** [comment]
Yeah I think those variables were left out to limit the theme-ability. Not every variable needs to have an override. Some variables are scoped to blocks simply to make editing that block easier instead of having to change multiple values.

**Comment by jimmynotjim** [comment]
Assuming we can close this @anselmbradford?
